# 端口号
server:
  port: 8888

spring:
  application:
    name: futures
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://101.32.126.44:3306/trade?useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true&autoReconnect=true
    url: jdbc:mysql://localhost:3306/trade?useUnicode=true&characterEncoding=utf-8&useSSL=false&useAffectedRows=true&autoReconnect=true
    username: trade
    password: 123456
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 600000
      maximum-pool-size: 500
      max-lifetime: 1800000
      minimum-idle: 20
      validation-timeout: 3000
      idle-timeout: 60000

# mybatis-plus配置信息
mybatis-plus:
  global-config:
    db-config:
      insert-strategy: ignored
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    poolMaximumActiveConnections: 100
    poolMaximumIdleConnections: 20
    poolTimeToWait: 10

logging:
  config: classpath:logback-config.xml
  level:
    com.wizard.mapper: debug

# 飞书配置
FEISHU:
  FS_WEBHOOK_URL: https://open.feishu.cn/open-apis/bot/v2/hook/92dac6e7-2eae-455c-aa77-274e73e6bf3f
  APP_ID: cli_a667ab5d10ae5013
  APP_SECRET: kctKLQrmI4CxRfzrkNIWBeWGyOxixZJx

# 代理地址
PROXY:
#  URL: https://trade1818.top/https/fapi.binance.com
  URL: https://fapi.binance.com
BINANCE:
  API_KEY: bLRZ0KadDOFwzi4wykvUaztZPqEy1vVtqXHSZTiJsXZh8QbXpKAJBhTZxnwRzpA8
  SECRET_KEY: MlUXOcLE79Bx4ld7YnYS6hSjKzxhgOOzEdT8sS9bHZ1GLYFrITMYbxE8WHt7y3Hg

# 持仓变动
ADD_NUMBER: 1.05

#LOG_PATH: /Users/yueyaoli/Documents/中科睿见/本地项目日志/
LOG_PATH: /monitor/
