
# 飞书配置
FEISHU:
  FS_WEBHOOK_URL: https://open.feishu.cn/open-apis/bot/v2/hook/92dac6e7-2eae-455c-aa77-274e73e6bf3f

# 代理地址
PROXY:
  URL: https://trade1818.top/https/fapi.binance.com
#  URL: https://fapi.binance.com

# 持仓变动
ADD_NUMBER: 1.2

BINANCE:
  API_KEY: bLRZ0KadDOFwzi4wykvUaztZPqEy1vVtqXHSZTiJsXZh8QbXpKAJBhTZxnwRzpA8
  SECRET_KEY: MlUXOcLE79Bx4ld7YnYS6hSjKzxhgOOzEdT8sS9bHZ1GLYFrITMYbxE8WHt7y3Hg

